{
 "title": "INFORMACION",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_Filter", "query": "localhost" }
  ]
 },
 "panels": [
  {
   "title": "USO DEL CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "db_psa2",
     "rawSql": "SELECT fecha, cpu FROM db_psa2.servers_data WHERE host LIKE CONCAT('%','$host_Filter','%')"
    }
   ]
  },
  {
   "title": "Memoria Ram",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "db_psa2",
     "rawSql": "SELECT fecha, mem_total, mem_libre, mem_usada FROM db_psa2.servers_data WHERE host LIKE CONCAT('%','$host_Filter', '%') ORDER BY fecha DESC "
    }
   ]
  },
  {
   "title": "Almacenamiento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "db_psa2",
     "rawSql": "SELECT fecha, disco_total, disco_libre, disco_usado FROM db_psa2.servers_data WHERE host LIKE CONCAT('%','$host_Filter','%')  ORDER BY fecha DESC "
    }
   ]
  },
  {
   "title": "Red",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db_psa2",
     "rawSql": "SELECT fecha, data_rx as 'RED: MB Recibidos', data_tx as 'RED: MB Enviados' FROM db_psa2.servers_data WHERE host LIKE CONCAT('%','$host_Filter','%') ORDER BY fecha ASC "
    }
   ]
  },
  {
   "title": "Tabla de información ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "db_psa2",
     "rawSql": "SELECT fecha, host, cpu as 'CPU%', disco_total as 'disco_total GB', disco_usado as 'disco_usado GB', disco_libre as 'disco_libre GB', mem_total as 'mem_total MB', mem_usada as 'mem_usada MB', mem_libre as 'mem_libre MB', data_rx as 'RED: MB Recibido', data_tx as 'RED: MB Enviados' FROM db_psa2.servers_data WHERE host LIKE CONCAT('%','$host_Filter', '%') ORDER BY fecha DESC LIMIT 5 "
    }
   ]
  }
 ]
}